### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Jason-Cooke**

### CODE REVIEW

**Comment by TimNZ** [comment]
Please don't force me to commit this change!! 

Funny typos need to be preserved. 

:)

**Comment by Jason-Cooke** [comment]
Lol fair enough!

**Comment by TimNZ** [comment]
BTW if you didn't see, Xero have forked this for their official SDK.
https://github.com/XeroAPI/xero-node

**Comment by Jason-Cooke** [comment]
Cheers for the link!

**Pull request merged**
